import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
type View="loading"|"initialize"|"login"|"ready"; type AssetState="normal"|"synchronizing"|"exception";
type Asset={id:string;path:string;jav_code:string|null;title:string|null;artwork_url:string|null;captured_date:string;state:AssetState;exception:string|null};
type AssetDetail={id:string;path:string;title:string|null;actors:Array<{name:string;poster_url:string|null;actor_folder_url:string|null}>;studio:string|null;release_date:string|null;runtime_minutes:number|null;director:string|null;tags:string[];plot:string|null;parse_status:"valid"|"missing"|"invalid";source_path:string|null;state:AssetState;exception:string|null};
type Page={items:Asset[];groups:Array<{date:string;count:number}>;page:number;total:number;total_pages:number}; type Health={state:string;mode:string|null};
type Task={id:string;task_type:string;media_root:string;kind:"preview"|"mutation";status:"queued"|"running"|"completed"|"failed"|"interrupted";created_at:number;error:string|null;items:Array<{id:number;kind:string;path:string|null;status:string;message:string|null}>};
type ActorFolder={name:string;movie_count:number;hard_link_count:number;logical_size:number;reclaimable_space:number;poster_url:string|null};
const labels:Record<AssetState,string>={normal:"Normal",synchronizing:"Synchronizing",exception:"Exception"};
function App(){
 const token=new URLSearchParams(location.search).get("token"),[view,setView]=useState<View>(token?"initialize":"loading"),[password,setPassword]=useState(""),[message,setMessage]=useState("");
 const [assets,setAssets]=useState<Page>({items:[],groups:[],page:1,total:0,total_pages:0}),[query,setQuery]=useState(""),[filter,setFilter]=useState<AssetState|"">(""),[health,setHealth]=useState<Health|null>(null),[page,setPage]=useState(1),[nav,setNav]=useState<"assets"|"actors"|"tasks"|"settings">("assets");
 const [actors,setActors]=useState<ActorFolder[]>([]),[confirmActor,setConfirmActor]=useState<ActorFolder|null>(null),[actorBusy,setActorBusy]=useState(false);
 const [selected,setSelected]=useState<Asset|null>(null),[detail,setDetail]=useState<AssetDetail|null>(null),[detailLoading,setDetailLoading]=useState(false);
 const [tasks,setTasks]=useState<Task[]>([]),[mediaRoot,setMediaRoot]=useState(""),[mode,setMode]=useState<"preview"|"apply">("preview"),[operation,setOperation]=useState("delete_ad_files");
 useEffect(()=>{if(!token)fetch("/api/v1/status").then(r=>{if(r.ok)setView("ready");else{setView("login");if(r.status===503)setMessage("Run rust-jav administrator init locally first.")}})},[token]);
 useEffect(()=>{if(view!=="ready")return;const timer=setTimeout(()=>void loadAssets(),180);return()=>clearTimeout(timer)},[view,query,filter,page]);
 useEffect(()=>{if(nav==="tasks")void loadTasks()},[nav]);
 useEffect(()=>{if(nav==="actors")void loadActors()},[nav]);
 async function loadAssets(){const p=new URLSearchParams({page:String(page),per_page:"48"});if(query)p.set("q",query);if(filter)p.set("state",filter);const[a,h]=await Promise.all([fetch(`/api/v1/assets?${p}`),fetch("/api/v1/assets/health")]);if(a.ok)setAssets(await a.json());if(h.ok)setHealth(await h.json())}
 async function scan(){setMessage("Reconciling filesystem…");const r=await fetch("/api/v1/assets/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"manual"})});setMessage(r.ok?"Asset Index reconciled.":await r.text());await loadAssets()}
 async function inspect(asset:Asset){setSelected(asset);setDetail(null);setDetailLoading(true);const response=await fetch(`/api/v1/assets/${asset.id}`);if(response.ok)setDetail(await response.json());else setMessage("Asset details could not be loaded.");setDetailLoading(false)}
 function closeInspector(){setSelected(null);setDetail(null)}
 async function submit(e:FormEvent){e.preventDefault();const init=view==="initialize",r=await fetch(`/api/v1/auth/${init?"initialize":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(init?{token,password}:{password})});setPassword("");if(!r.ok){setMessage(r.status===401?"Incorrect password.":"Request rejected.");return}if(init){history.replaceState({},"","/");setView("login");setMessage("Administrator initialized. Sign in to continue.")}else location.assign("/")}
 async function logout(){await fetch("/api/v1/auth/logout",{method:"POST"});setView("login")}
 async function loadTasks(){const response=await fetch("/api/v1/tasks");if(response.ok){const recovered=(await response.json()) as Task[];setTasks(recovered);recovered.filter(task=>["queued","running"].includes(task.status)).forEach(task=>watchTask(task.id))}}
 function watchTask(id:string){const source=new EventSource(`/api/v1/tasks/${id}/events`);source.addEventListener("task",event=>{const task=JSON.parse((event as MessageEvent).data) as Task;setTasks(current=>[task,...current.filter(item=>item.id!==task.id)]);if(["completed","failed","interrupted"].includes(task.status))source.close()})}
 async function createTask(event:FormEvent){event.preventDefault();setMessage("");const response=await fetch("/api/v1/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_type:"operations",media_root:mediaRoot,mode,operations:[operation]})});if(!response.ok){setMessage(await response.text()||"Task request rejected.");return}const task=(await response.json()) as Task;setTasks(current=>[task,...current]);watchTask(task.id)}
 async function loadActors(){const response=await fetch("/api/v1/actors");if(response.ok)setActors(await response.json());else setMessage(await response.text()||"Actor Folders could not be loaded.")}
 async function requestActorRemoval(actor:ActorFolder){setActorBusy(true);const response=await fetch(`/api/v1/actors/${encodeURIComponent(actor.name)}`);if(response.ok)setConfirmActor(await response.json());else setMessage(await response.text()||"Actor Folder could not be revalidated.");setActorBusy(false)}
 async function removeActor(){if(!confirmActor)return;setActorBusy(true);const response=await fetch(`/api/v1/actors/${encodeURIComponent(confirmActor.name)}`,{method:"DELETE"});if(!response.ok){setMessage(await response.text()||"Actor Folder removal was rejected.");setActorBusy(false);return}const task=(await response.json()) as Task;setTasks(current=>[task,...current]);watchTask(task.id);setConfirmActor(null);setMessage("Actor Folder removal started as a Management Task.");await loadActors();setActorBusy(false)}
 const grouped=useMemo(()=>assets.groups.map(group=>({group,items:assets.items.filter(a=>a.captured_date===group.date)})).filter(g=>g.items.length),[assets]);
 if(view==="loading")return <div className="auth">Checking session…</div>;
 if(view==="initialize"||view==="login")return <main className="auth"><div className="brand-mark">◆</div><p className="eyebrow">RUST—JAV</p><h1>{view==="initialize"?"Initialize Administrator":"Welcome back"}</h1><form onSubmit={submit}><label htmlFor="password">Password</label><input id="password" type="password" minLength={12} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/><button type="submit">{view==="initialize"?"Initialize":"Sign in"}</button></form>{message&&<p role="status">{message}</p>}</main>;
 return <div className={`shell ${selected?"inspecting":""}`}><aside className="sidebar"><div className="logo"><span>◆</span><div><b>rust-jav</b><small>Media library</small></div></div><nav><p>LIBRARY</p><button className={nav==="assets"?"active":""} onClick={()=>setNav("assets")}><span>▦</span> All Assets <em>{assets.total}</em></button><button><span>◷</span> Recently Added</button><button className={nav==="actors"?"active":""} onClick={()=>setNav("actors")}><span>♙</span> Actors <em>{actors.length}</em></button><p>MANAGE</p><button className={nav==="tasks"?"active":""} onClick={()=>setNav("tasks")}><span>☷</span> Management Tasks</button><button onClick={()=>{setNav("assets");setFilter("exception");setPage(1)}}><span>⚠</span> Exceptions</button></nav><div className="root-card"><small>ASSET INDEX</small><b><i className={`health-dot ${health?.state}`}/>{health?.state??"Loading"}</b><span>{health?.mode?`Last ${health.mode} scan`:"Filesystem authoritative"}</span></div><button className="signout" onClick={logout}>Sign out</button></aside>
 <main className="content"><header><div><p className="eyebrow">MEDIA LIBRARY</p><h1>{nav==="assets"?"All Assets":nav==="actors"?"Actor Folders":nav==="tasks"?"Management Tasks":"Settings"}</h1><small>{nav==="tasks"?`${tasks.length} durable tasks · live lifecycle recovery`:nav==="actors"?`${actors.length} derived Actor Folders · regenerable from NFO metadata`:`${assets.total} indexed Media Assets · filesystem authoritative`}</small></div>{nav==="assets"&&<button className="scan" onClick={scan}>↻ <span>Reconcile</span></button>}</header>{nav==="assets"&&<><div className="toolbar"><label className="search">⌕<input aria-label="Search assets" placeholder="Search code, title, or path" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><div className="filters"><button className={!filter?"selected":""} onClick={()=>setFilter("")}>All</button><button className={filter==="exception"?"selected":""} onClick={()=>{setFilter("exception");setPage(1)}}>Exceptions</button></div></div>{message&&<p className="notice" role="status">{message}</p>}<div className="library">{grouped.length===0?<Empty/>:grouped.map(({group,items})=><section className="date-group" key={group.date}><div className="date-heading"><h2>{formatDate(group.date)}</h2><span>{group.count} items</span></div><div className="asset-grid">{items.map(a=><article className={`asset-card ${selected?.id===a.id?"selected":""}`} key={a.id}><button className="asset-select" onClick={()=>void inspect(a)} aria-label={`Inspect ${a.jav_code??a.title??"asset"}`}><div className="poster">{a.artwork_url?<img loading="lazy" src={a.artwork_url} alt=""/>:<div className="placeholder"><span>◇</span><small>NO ARTWORK</small></div>}<span className={`state ${a.state}`} title={a.exception??labels[a.state]}/></div><div className="meta"><b>{a.jav_code??a.title??"Unidentified"}</b><span>{a.title??a.path.split("/").pop()}</span><small className={`state-label ${a.state}`}>{labels[a.state]}</small></div></button></article>)}</div></section>)}</div>{assets.total_pages>1&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {assets.total_pages}</span><button disabled={page===assets.total_pages} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}{nav==="actors"&&<ActorFolders actors={actors} busy={actorBusy} remove={requestActorRemoval}/>} {nav==="tasks"&&<TaskPanel tasks={tasks} mediaRoot={mediaRoot} setMediaRoot={setMediaRoot} mode={mode} setMode={setMode} operation={operation} setOperation={setOperation} createTask={createTask} refresh={loadTasks} message={message}/>}</main>
 {selected&&<AssetInspector asset={selected} detail={detail} loading={detailLoading} close={closeInspector}/>}
 {confirmActor&&<ActorRemovalDialog actor={confirmActor} busy={actorBusy} cancel={()=>setConfirmActor(null)} remove={()=>void removeActor()}/>}<nav className="bottom-nav"><button className={nav==="assets"?"active":""} onClick={()=>setNav("assets")}><span>▦</span>Library</button><button className={nav==="actors"?"active":""} onClick={()=>setNav("actors")}><span>♙</span>Actors</button><button className={nav==="tasks"?"active":""} onClick={()=>setNav("tasks")}><span>☷</span>Tasks</button></nav></div>}
function AssetInspector({asset,detail,loading,close}:{asset:Asset;detail:AssetDetail|null;loading:boolean;close:()=>void}){const[tab,setTab]=useState<"overview"|"nfo">("overview");useEffect(()=>setTab("overview"),[asset.id]);useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};addEventListener("keydown",escape);return()=>removeEventListener("keydown",escape)},[close]);return <aside className="asset-inspector" role="dialog" aria-modal="false" aria-labelledby="asset-detail-title"><div className="sheet-handle"/><button autoFocus className="inspector-close" onClick={close} aria-label="Close asset details">×</button><div className="inspector-hero">{asset.artwork_url?<img src={asset.artwork_url} alt=""/>:<div className="placeholder"><span>◇</span><small>NO ARTWORK</small></div>}<div><strong id="asset-detail-title">{asset.jav_code??"Media Asset"}</strong><span>{detail?.title??asset.title??asset.path.split("/").pop()}</span></div></div><div className="detail-tabs" role="tablist" aria-label="Asset details"><button role="tab" aria-selected={tab==="overview"} onClick={()=>setTab("overview")}>Overview</button><button role="tab" aria-selected={tab==="nfo"} onClick={()=>setTab("nfo")}>NFO</button></div>{loading?<p className="detail-loading" role="status">Loading asset details…</p>:detail&&tab==="overview"?<div role="tabpanel" className="detail-panel"><StateBanner detail={detail}/><h2>Actors</h2>{detail.actors.length?<div className="actor-grid">{detail.actors.map(actor=>actor.actor_folder_url?<a className="actor-poster" href={actor.actor_folder_url} key={actor.name}>{actor.poster_url?<img src={actor.poster_url} alt={`${actor.name} poster`}/>:<span className="actor-silhouette">♙</span>}<span><b>{actor.name}</b><small>Actor Folder →</small></span></a>:<div className="actor-poster" key={actor.name}><span className="actor-silhouette">♙</span><span><b>{actor.name}</b><small>Actor Folder unavailable</small></span></div>)}</div>:<p className="muted">No actors in this NFO.</p>}<dl className="detail-list"><Info k="Studio" v={detail.studio}/><Info k="Release" v={detail.release_date}/><Info k="Source video" v={detail.path}/></dl></div>:detail&&<div role="tabpanel" className="detail-panel"><p className="plot">{detail.plot??"No plot in this NFO."}</p><dl className="detail-list"><Info k="Title" v={detail.title}/><Info k="Studio" v={detail.studio}/><Info k="Release date" v={detail.release_date}/><Info k="Runtime" v={detail.runtime_minutes?`${detail.runtime_minutes} minutes`:null}/><Info k="Director" v={detail.director}/><Info k="Parse status" v={detail.parse_status}/><Info k="NFO path" v={detail.source_path}/></dl><div className="tags">{detail.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>}</aside>}
function StateBanner({detail}:{detail:AssetDetail}){return <div className={`state-banner ${detail.state}`}><b>{labels[detail.state]} Asset</b><span>{detail.exception??(detail.state==="synchronizing"?"Automatic reconciliation is in progress.":"Local metadata is valid.")}</span></div>}
function Info({k,v}:{k:string;v:string|null}){return <div><dt>{k}</dt><dd>{v??"Not provided"}</dd></div>}
function Empty(){return <div className="empty"><span>◇</span><h2>No Media Assets</h2><p>Configure a Media Root, then reconcile the filesystem.</p></div>}
function ActorFolders({actors,busy,remove}:{actors:ActorFolder[];busy:boolean;remove:(actor:ActorFolder)=>Promise<void>}){return actors.length===0?<div className="empty"><span>♙</span><h2>No Actor Folders</h2><p>Generate the derived Actor View from NFO metadata.</p></div>:<div className="actor-folder-grid">{actors.map(actor=><article className="actor-folder-card" key={actor.name}><div className="actor-folder-poster">{actor.poster_url?<img src={actor.poster_url} alt={`${actor.name} poster`}/>:<span>♙</span>}</div><div className="actor-folder-meta"><h2>{actor.name}</h2><p>{actor.movie_count} movie director{actor.movie_count===1?"y":"ies"} · {actor.hard_link_count} hard link{actor.hard_link_count===1?"":"s"}</p><dl><div><dt>Logical Size</dt><dd>{formatBytes(actor.logical_size)}</dd></div><div><dt>Reclaimable Space</dt><dd>{formatBytes(actor.reclaimable_space)}</dd></div></dl><button disabled={busy} onClick={()=>void remove(actor)}>Remove Actor Folder…</button></div></article>)}</div>}
function ActorRemovalDialog({actor,busy,cancel,remove}:{actor:ActorFolder;busy:boolean;cancel:()=>void;remove:()=>void}){return <div className="dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)cancel()}}><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="remove-actor-title"><p className="eyebrow">SAFE DERIVED-PATH REMOVAL</p><h2 id="remove-actor-title">Remove {actor.name}?</h2><p>Only paths under this Actor Folder will be unlinked. Source Media Assets, NFO metadata, and Jellyfin items will not be removed.</p><dl><div><dt>Actor Folder</dt><dd>{actor.name}</dd></div><div><dt>Movie directories</dt><dd>{actor.movie_count}</dd></div><div><dt>Hard links</dt><dd>{actor.hard_link_count}</dd></div><div><dt>Logical Size</dt><dd>{formatBytes(actor.logical_size)}</dd></div><div><dt>Reclaimable Space</dt><dd>{formatBytes(actor.reclaimable_space)}</dd></div></dl><small>These values were recomputed from the filesystem for this confirmation.</small><div className="dialog-actions"><button onClick={cancel} disabled={busy}>Cancel</button><button className="danger" onClick={remove} disabled={busy}>{busy?"Starting…":"Remove via Management Task"}</button></div></section></div>}
function TaskPanel({tasks,mediaRoot,setMediaRoot,mode,setMode,operation,setOperation,createTask,refresh,message}:{tasks:Task[];mediaRoot:string;setMediaRoot:(v:string)=>void;mode:"preview"|"apply";setMode:(v:"preview"|"apply")=>void;operation:string;setOperation:(v:string)=>void;createTask:(e:FormEvent)=>void;refresh:()=>Promise<void>;message:string}){return <div className="task-dashboard"><section className="task-create"><h2>New task</h2><form className="task-form" onSubmit={createTask}><label htmlFor="media-root">Media Root</label><input id="media-root" value={mediaRoot} onChange={e=>setMediaRoot(e.target.value)} placeholder="/media/library" required/><label htmlFor="operation">Operation</label><select id="operation" value={operation} onChange={e=>setOperation(e.target.value)}><option value="delete_ad_files">Delete ad files</option><option value="standardize_names">Standardize names</option><option value="clean_empty_dirs">Clean empty directories</option><option value="remove_duplicates">Remove duplicates</option></select><label htmlFor="mode">Mode</label><select id="mode" value={mode} onChange={e=>setMode(e.target.value as "preview"|"apply")}><option value="preview">Preview</option><option value="apply">Apply changes</option></select><button type="submit">Start task</button></form>{message&&<p className="notice" role="status">{message}</p>}</section><section className="task-history"><div className="task-title"><div><h2>Lifecycle</h2><p>Durable history and per-item outcomes</p></div><button className="refresh" onClick={()=>void refresh()}>Refresh</button></div>{tasks.length===0?<p className="task-empty">No Management Tasks yet.</p>:<ol className="tasks">{tasks.map(task=><li key={task.id}><div className="task-summary"><span className={`status status-${task.status}`}>{task.status}</span><strong>{task.kind}</strong><span className="task-root">{task.media_root}</span></div><small>{task.items.length} item outcome{task.items.length===1?"":"s"} · {task.id}</small>{task.error&&<p className="task-error">{task.error}</p>}{task.items.length>0&&<ul className="task-items">{task.items.map(item=><li key={item.id}><span>{item.status}</span><b>{item.kind}</b><code>{item.path??"—"}</code>{item.message&&<small>{item.message}</small>}</li>)}</ul>}</li>)}</ol>}</section></div>}
function formatDate(v:string){return new Intl.DateTimeFormat(undefined,{month:"long",day:"numeric",year:"numeric"}).format(new Date(`${v}T00:00:00`))}
function formatBytes(value:number){if(value===0)return "0 B";const units=["B","KB","MB","GB","TB"],index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return `${(value/1024**index).toLocaleString(undefined,{maximumFractionDigits:1})} ${units[index]}`}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
